name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Install
      run: yarn install

    - name: Eslint Test
      run: yarn run lint

    - name: Build site
      run: yarn run build
